import{a as y,S as L,i as f}from"./assets/vendor-64b55ca9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();async function h(r,o,c){const n="https://pixabay.com",e="/api/",t="42307570-a64cb029cc8427df0f0b3ddcd",a=`${n}${e}`,u={key:t,image_type:"photo",orientation:"horizontal",safesearch:!0,q:r,per_page:c,page:o};return(await y.get(a,{params:u})).data}const b="/goit-js-hw-12/assets/bi_x-octagon-42c005e5.svg",s={renderMarkup(r){const o=r.map(n=>{const{webformatURL:e,largeImageURL:t,tags:a,likes:u,views:p,comments:g,downloads:v}=n;return`<li class="gallery-item">
<a class="gallery-link" href=${t}>
<img class="gallery-image" src=${e} alt="${a}" />
</a><div class="options-div"><div class="item-div"><h4 class="item-div-name">Likes</h4>
  <p class="item-div-text">${u}</p></div><div class="item-div"><h4 class="item-div-name">Views</h4>
  <p class="item-div-text">${p}</p></div><div class="item-div"><h4 class="item-div-name">Comments</h4>
  <p class="item-div-text">${g}</p></div><div class="item-div"><h4 class="item-div-name">Downloads</h4>
  <p class="item-div-text">${v}</p></div></div>
</li>`}).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",o);var c=new L(".gallery a",{captionPosition:"bottom",captionsData:"alt",className:"modal"});c.refresh()},removeMarkup(){document.querySelector(".gallery").innerHTML=""},setLoader(){document.querySelector(".load-button").insertAdjacentHTML("afterend",'<span class="loader"></span>')},removeLoader(){document.querySelector(".loader").remove()},loadButtonStatus(r,o){r<o?document.querySelector(".load-button").classList.remove("hidden"):document.querySelector(".load-button").classList.add("hidden")},hideLoadButton(){document.querySelector(".load-button").classList.add("hidden")}};let l,i,d;const m=15,S=document.querySelector(".form");S.addEventListener("submit",w);const x=document.querySelector(".load-button");x.addEventListener("click",q);async function w(r){if(l=r.target.elements.searchInput.value.trim(),s.hideLoadButton(),r.preventDefault(),s.removeMarkup(),r.target.reset(),l){s.setLoader(),i=1;try{const o=await h(l,i,m);if(o.hits.length===0){s.removeLoader(),f.error({timeout:3e3,message:"Sorry, there are no images matching your search query. Please try again!",maxWidth:"432px",messageColor:"#fff",messageSize:"16px",messageLineHeight:"1.5",backgroundColor:"#ef4040",position:"topRight",titleColor:"#fff",titleSize:"16px",titleLineHeight:"1.5",iconUrl:b});return}else d=Math.ceil(o.totalHits/m),s.renderMarkup(o.hits)}catch{console.log("Mistake from server")}s.removeLoader(),s.loadButtonStatus(i,d)}}async function q(){s.setLoader(),i+=1;const r=await h(l,i,m);s.renderMarkup(r.hits),s.removeLoader(),s.loadButtonStatus(i,d),i>=d&&f.info({timeout:3e3,message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),window.scrollBy({behavior:"smooth",top:2*document.querySelector(".gallery-item").getBoundingClientRect().height})}
//# sourceMappingURL=commonHelpers.js.map
