import{a as v,S as h}from"./assets/vendor-3cfff7f0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();async function m(s,r){const i="https://pixabay.com",a="/api/",e="42307570-a64cb029cc8427df0f0b3ddcd",t=`${i}${a}`,o={key:e,image_type:"photo",orientation:"horizontal",safesearch:!0,q:s,per_page:15,page:r};return(await v.get(t,{params:o})).data}const n={renderMarkup(s){const r=s.map(a=>{const{webformatURL:e,largeImageURL:t,tags:o,likes:d,views:u,comments:p,downloads:f}=a;return`<li class="gallery-item">
<a class="gallery-link" href=${t}>
<img class="gallery-image" src=${e} alt="${o}" />
</a><div class="options-div"><div class="item-div"><h4 class="item-div-name">Likes</h4>
  <p class="item-div-text">${d}</p></div><div class="item-div"><h4 class="item-div-name">Views</h4>
  <p class="item-div-text">${u}</p></div><div class="item-div"><h4 class="item-div-name">Comments</h4>
  <p class="item-div-text">${p}</p></div><div class="item-div"><h4 class="item-div-name">Downloads</h4>
  <p class="item-div-text">${f}</p></div></div>
</li>`}).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",r);var i=new h(".gallery a",{captionPosition:"bottom",captionsData:"alt",className:"modal"});i.refresh()},removeMarkup(){document.querySelector(".gallery").innerHTML=""},setLoader(){document.querySelector(".load-button").insertAdjacentHTML("afterend",'<span class="loader"></span>')},removeLoader(){document.querySelector(".loader").remove()}},g=document.querySelector(".form");g.addEventListener("submit",L);const y=document.querySelector(".load-button");y.addEventListener("click",b);let c,l;async function L(s){if(s.preventDefault(),n.removeMarkup(),c=s.target.elements.searchInput.value.trim(),s.target.reset(),c){n.setLoader(),l=1;const r=await m(c,l);n.renderMarkup(r.hits)}}async function b(s){l+=1;const r=await m(c,l);n.renderMarkup(r.hits)}
//# sourceMappingURL=commonHelpers.js.map
